/*
1) join table에서 그대로 값 가져오기
  --463sec ,25478row
*/

SELECT
	       CA02.CLNT_ID||'-'||CA02.CONT_NO||'-'||CA02.BOND_SEQ										 AS 채권번호
		  ,	Comm_Func.f_get_code_name('MAIL_SEND_PLAC_DIVI', c8.mail_send_plac_divi)  AS 우편물발송지구분
		  , Comm_Func.f_get_code_name('MAIL_STEP',C8.curr_step)						  AS 우편물진행상태
		  , C8.retn_ymd    															  AS 우편물반송일자
		  , Comm_Func.f_get_code_name('MAIL_RETN_RESN', C8.retn_resn)  				  AS 우편물반송사유
		  , Comm_Func.f_get_code_name('SEND_LMIT_RESN_CODE', C8.send_lmit_resn_code)  as 우편물발송금지사유
FROM
   (SELECT
	       CA01.TEAM_CODE
			,CA01.STAF_ID
			,CA01.LOAN_NO
			,CA01.VTAC_BANK_CODE
			,CA01.VTAC_NO
			,CA01.RQST_YMD
			,CA01.CPLT_LAST_YMD
			,CA01.ATAP_AMT_PAMT
			,CA01.ATAP_AMT_INT
			,CA01.ATAP_AMT_EAMT
			,CA01.BOND_RAMT
			,CA01.CONT_YMD
			,CA01.CLNT_ID
			,CA01.CONT_NO
			,CA01.BOND_SEQ
			,CA01.END_DIVI
			,CA01.END_DATE
			,CA02.CUST_NAME
			,CA02.CUST_ID
			,CA02.DEBT_DIVI
			,CA02.PSRS_STEP
			,CA02.BKRT_IMMU_STEP
			FROM
	       CA01BOND CA01
	     , CA02RELN CA02
	     WHERE 1=1
	     	AND CA01.CLNT_ID  = CA02.CLNT_ID
			AND CA01.BOND_SEQ = CA02.BOND_SEQ
			AND CA01.CONT_NO  = CA02.CONT_NO
			AND CA01.USE_YN = ' '
			AND CA02.USE_YN = ' '
         ) CA02
	, (SELECT A.CLNT_ID
			  ,A.CUST_ID
			  ,B.LOAN_NO
			  ,A.MAIL_SEND_PLAC_DIVI
			  ,A.CURR_STEP
			  ,A.RETN_YMD
			  ,A.RETN_RESN
			  ,A.SEND_LMIT_RESN_CODE
			  ,RANK() OVER(PARTITION BY A.CLNT_ID, A.CUST_ID, B.LOAN_NO ORDER BY A.MAIL_APLY_YMD DESC, A.MAIL_ADMN_NO DESC) AS "MAIL_RANK"
	   FROM CA08MLLN B
	   		,CA08MAIL A
	  WHERE A.CNCL_YN='N'
	  AND A.CURR_STEP NOT IN('02','05')
	  AND A.USE_YN=' '
	  AND B.MAIL_ADMN_NO=A.MAIL_ADMN_NO
	  AND B.SEND_LMIT_RESN_CODE='01'
	  ) C8   --우편물
WHERE  1=1

	AND CA02.CLNT_ID=C8.CLNT_ID(+)
	AND CA02.CUST_ID=C8.CUST_ID(+)
	AND CA02.LOAN_NO=C8.LOAN_NO(+)
	AND C8.MAIL_RANK(+)=1

	AND CA02.TEAM_CODE IN('8010','2032','2033','4060','4020','4045','4050', '2060')--팀코드(8010: 전략영업팀), 마케팅지원팀2060도 포함
	AND CA02.CLNT_ID NOT IN ('001', '002', '003')  	  --전략영업팀 보유 위탁사


	AND CA02.END_DIVI='00' -- 진행

;
/*
2) SubQuery마다 rank해서 값 가져오기
  --189sec    ,25354
*/
SELECT
CA02.CLNT_ID||'-'||CA02.CONT_NO||'-'||CA02.BOND_SEQ										 AS 채권번호
,(SELECT Comm_Func.f_get_code_name('MAIL_SEND_PLAC_DIVI', c8.mail_send_plac_divi)
	FROM   (SELECT   A.CLNT_ID
				  ,A.CUST_ID
				  ,B.LOAN_NO
				  ,A.MAIL_SEND_PLAC_DIVI
				  ,RANK() OVER(PARTITION BY A.CLNT_ID, A.CUST_ID,B.LOAN_NO ORDER BY A.MAIL_APLY_YMD DESC, A.MAIL_ADMN_NO DESC, B.SEQ DESC) AS "MAIL_RANK"
		   FROM CA08MLLN B
		   		,CA08MAIL A
		  WHERE A.CNCL_YN='N'
		  AND A.CURR_STEP NOT IN('02','05')
		  AND A.USE_YN=' '
		  AND B.MAIL_ADMN_NO=A.MAIL_ADMN_NO
		  AND B.SEND_LMIT_RESN_CODE='01'
		  ) C8   --우편물
	WHERE C8.CLNT_ID=CA02.CLNT_ID
	AND C8.CUST_ID=CA02.CUST_ID
	AND C8.LOAN_NO=CA02.LOAN_NO
	AND C8.MAIL_RANK=1 )																 AS 우편물발송지구분
,(SELECT Comm_Func.f_get_code_name('MAIL_STEP',C8.curr_step)
	FROM   (SELECT  A.CLNT_ID
				  ,A.CUST_ID
				  ,B.LOAN_NO
				 ,A.CURR_STEP
				  ,RANK() OVER(PARTITION BY A.CLNT_ID, A.CUST_ID, B.LOAN_NO ORDER BY A.MAIL_APLY_YMD DESC, A.MAIL_ADMN_NO DESC, B.SEQ DESC) AS "MAIL_RANK"
		   FROM CA08MLLN B
		   		,CA08MAIL A
		  WHERE A.CNCL_YN='N'
		  AND A.CURR_STEP NOT IN('02','05')
		  AND A.USE_YN=' '
		  AND B.MAIL_ADMN_NO=A.MAIL_ADMN_NO
		  AND B.SEND_LMIT_RESN_CODE='01'
		  ) C8   --우편물
	WHERE C8.CLNT_ID=CA02.CLNT_ID
	AND C8.CUST_ID=CA02.CUST_ID
	AND C8.LOAN_NO=CA02.LOAN_NO
	AND C8.MAIL_RANK=1  )																 AS 우편물진행상태
,(SELECT C8.retn_ymd
	FROM   (SELECT  A.CLNT_ID
				  ,A.CUST_ID
				  ,B.LOAN_NO
				  ,A.RETN_YMD
				  ,RANK() OVER(PARTITION BY A.CLNT_ID, A.CUST_ID,B.LOAN_NO ORDER BY A.MAIL_APLY_YMD DESC, A.MAIL_ADMN_NO DESC, B.SEQ DESC) AS "MAIL_RANK"
		   FROM CA08MLLN B
		   		,CA08MAIL A
		  WHERE A.CNCL_YN='N'
		  AND A.CURR_STEP NOT IN('02','05')
		  AND A.USE_YN=' '
		  AND B.MAIL_ADMN_NO=A.MAIL_ADMN_NO
		  AND B.SEND_LMIT_RESN_CODE='01'
		  ) C8   --우편물
	WHERE C8.CLNT_ID=CA02.CLNT_ID
	AND C8.CUST_ID=CA02.CUST_ID
	AND C8.LOAN_NO=CA02.LOAN_NO
	AND C8.MAIL_RANK=1  )																 AS 우편물반송일자
,(SELECT Comm_Func.f_get_code_name('MAIL_RETN_RESN', C8.retn_resn)
	FROM   (SELECT  A.CLNT_ID
				  ,A.CUST_ID
				  ,B.LOAN_NO
				  ,A.RETN_RESN
				  ,RANK() OVER(PARTITION BY A.CLNT_ID, A.CUST_ID, B.LOAN_NO ORDER BY A.MAIL_APLY_YMD DESC, A.MAIL_ADMN_NO DESC, B.SEQ DESC) AS "MAIL_RANK"
		   FROM CA08MLLN B
		   		,CA08MAIL A
		  WHERE A.CNCL_YN='N'
		  AND A.CURR_STEP NOT IN('02','05')
		  AND A.USE_YN=' '
		  AND B.MAIL_ADMN_NO=A.MAIL_ADMN_NO
		  AND B.SEND_LMIT_RESN_CODE='01'
		  ) C8   --우편물
	WHERE C8.CLNT_ID=CA02.CLNT_ID
	AND C8.CUST_ID=CA02.CUST_ID
	AND C8.LOAN_NO=CA02.LOAN_NO
	AND C8.MAIL_RANK=1  )																 AS 우편물반송사유
,(SELECT Comm_Func.f_get_code_name('SEND_LMIT_RESN_CODE', C8.send_lmit_resn_code)
	FROM   (SELECT  A.CLNT_ID
				  ,A.CUST_ID
				  ,B.LOAN_NO
				  ,A.SEND_LMIT_RESN_CODE
				  ,RANK() OVER(PARTITION BY A.CLNT_ID, A.CUST_ID ORDER BY A.MAIL_APLY_YMD DESC, A.MAIL_ADMN_NO DESC, B.SEQ DESC) AS "MAIL_RANK"
		   FROM CA08MLLN B
		   		,CA08MAIL A
		  WHERE A.CNCL_YN='N'
		  AND A.CURR_STEP NOT IN('02','05')
		  AND A.USE_YN=' '
		  AND B.MAIL_ADMN_NO=A.MAIL_ADMN_NO
--		  AND B.SEND_LMIT_RESN_CODE='01'
		  ) C8   --우편물
	WHERE C8.CLNT_ID=CA02.CLNT_ID
	AND C8.CUST_ID=CA02.CUST_ID
	AND C8.LOAN_NO=CA02.LOAN_NO
	AND C8.MAIL_RANK=1  )																 AS 우편물발송금지사유
FROM
   (SELECT
	       CA01.TEAM_CODE
			,CA01.STAF_ID
			,CA01.LOAN_NO
			,CA01.VTAC_BANK_CODE
			,CA01.VTAC_NO
			,CA01.RQST_YMD
			,CA01.CPLT_LAST_YMD
			,CA01.ATAP_AMT_PAMT
			,CA01.ATAP_AMT_INT
			,CA01.ATAP_AMT_EAMT
			,CA01.BOND_RAMT
			,CA01.CONT_YMD
			,CA01.CLNT_ID
			,CA01.CONT_NO
			,CA01.BOND_SEQ
			,CA01.END_DIVI
			,CA01.END_DATE
			,CA02.CUST_NAME
			,CA02.CUST_ID
			,CA02.DEBT_DIVI
			,CA02.PSRS_STEP
			,CA02.BKRT_IMMU_STEP
			FROM
	       CA01BOND CA01
	     , CA02RELN CA02
	     WHERE 1=1
	     	AND CA01.CLNT_ID  = CA02.CLNT_ID
			AND CA01.BOND_SEQ = CA02.BOND_SEQ
			AND CA01.CONT_NO  = CA02.CONT_NO
			AND CA01.USE_YN = ' '
			AND CA02.USE_YN = ' '
         ) CA02
WHERE 1=1
	AND CA02.TEAM_CODE IN('8010','2032','2033','4060','4020','4045','4050', '2060')--팀코드(8010: 전략영업팀), 마케팅지원팀2060도 포함
	AND CA02.CLNT_ID NOT IN ('001', '002', '003')  	  --전략영업팀 보유 위탁사


	AND CA02.END_DIVI='00' -- 진행

